### ISSUE TITLE
Падает при запуске если выключен NFC

### ISSUE THREAD

**Issue by algel** [bafoed/plantain#1]
Samsung Galaxy S4 - Android 5.0.1
Если в момент запуска приложения NFC не был включен, то получаем сообщение от системы, что приложение было остановлено.

**Comment by VladBelosludtsev** [comment]
Asus Zenfone 2 ze551ml - Android 6.0.1
Та же ситуация.

**Comment by ttddttdd** [comment]
LG G3 (D855) - Android 6.0 (V30b-cis)
Та же ситуация.

**Comment by paveldenton** [comment]
Xperia Z3, так же

**Comment by bafoed** [comment]
Постараюсь найти ещё устройство и воспроизвести проблему.

**Comment by Konstantin555** [comment]
LG Nexus 4, android 5.1.1 - аналогичная ситуация.

**Comment by GrandLeak** [comment]
Падает из-за того что поле **mPendingIntent** в классе **MyActivity** не инициализировано при вызове метода **onResume()**. Соответственно, добавление проверки **mPendingIntent** на **null** в  **onResume()** устранит падение приложения.

**Comment by bafoed** [comment]
Должно быть исправлено в версии 1.0.1.
