### ISSUE TITLE
"Необработанная ошибка"

### ISSUE THREAD

**Issue by Glaed0ori** [bafoed/plantain#3]
При считывании выдаёт:
Необработанная ошибка #:Attempt to invoke virtual method 'void android.nfc.tech.MifareClassic.connect()' on a null object reference.

**Comment by goodic** [comment]
Та же проблема. Nexus5 AOSP 7.1

**Comment by bafoed** [comment]
Скорее всего, используется NFC-чип производства Broadcom — https://en.wikipedia.org/wiki/List_of_NFC-enabled_mobile_devices 
Для работы нужен чип производства NXP, я добавлю это в README.

**Comment by Malder2** [comment]
У меня - Необработанная ошибка #: Attempt to invoke virtual method 'short android.os.Bundle.getShort(java.lang.String)' on null object reference

Samsung Galaxy SIII 6.0.1

**Comment by Konstantin555** [comment]
Google Nexus 4, android 5.1.1 Broadcom BCM20793 - та же проблема. Для Broadcom'ов нет возможности версию сделать?

**Comment by goodic** [comment]
NXP требуется для получения ключа или есть иного рода особенности? Я это к тому, что зная ключ от своего кошелька реально сделать чтение баланса на карте? Или наш чип в принципе не пригоден?

**Comment by linko22** [comment]
Samsung A3 2015 - такая же ошибка

**Comment by Glaed0ori** [comment]
@bafoed Broadcom BCM20795 (Asus Zenfone 2) Да уж. Грустно. Придётся, по дешёвке покупать подходящий телефон.
Спасибо большое за информацию!

**Comment by Glaed0ori** [comment]
Вдруг кому-нибудь ещё информация потребуется, то пишите сюда.

**Comment by JamesWooLF** [comment]
Galaxy S7 and S7 Edge	NXP 67T05 and Samsung 81DGXS1 NFC
Пишет, что у меня правильная NXP, а всё равно та же ошибка.. странно.

**Comment by zartdinov** [comment]
Samsung A3 2017 - тоже самое

**Comment by linko22** [comment]
Samsung Galaxy S5 - работает

**Comment by bafoed** [comment]
В версии 1.0.1 добавлена проверка на поддержку карт Mifare чипом. Эта информация зашита производителем и не всегда соответствует действительности, поэтому возможность попробовать прочитать карту будет в любом случае.

@linko22 @JamesWooLF @zartdinov Был бы благодарен, если бы вы установили новую версию и сообщили бы, есть ли предупреждение о несовместимом чипе. Если есть — я, вероятно, ничем не смогу помочь, а если нет — буду ковырять дальше.

**Comment by bafoed** [comment]
#5

**Comment by linko22** [comment]
А3 2015: Внимание: на вашем устройстве не обнаружена поддержка карт Miifare, бла-бла-бла.

**Comment by JamesWooLF** [comment]
Samsung Galaxy s7, Внимание: на вашем устройстве не обнаружена поддержка карт Miifare/
При попытке прочесть карту выдаёт ту же ошибку, плюс стал выводить сообщение: "Тип метки NFC не поддерживается"

**Comment by Glaed0ori** [comment]
@JamesWooLF Уточните конкретную версию S7: G930*, G935* (и какие буквы в конце)

**Comment by JamesWooLF** [comment]
@Glaed0ori  G930FD

**Comment by Chrizt** [comment]
Подтверждаю, на S5 считывание работает, дамп сливается. Залить обратно не пробовал.

**Comment by bafoed** [comment]
Ошибка с _android.nfc.tech.MifareClassic.connect()_ связана с чипом и не имеет решения (в программе добавлено соответствующее уведомление.
Обсуждение ошибки с _ android.os.Bundle.getShort(java.lang.String)_ переносится в #5.
