### ISSUE TITLE
Необработанная ошибка #: File contains a path separator

### ISSUE THREAD

**Issue by weak4** [bafoed/plantain#6]
Xiaomi Mi5 с чипом NXP 66T17
Верно считывает баланс и количество поездок, но сохранить стейт невозможно
Необработанная ошибка #:File 7cw6/Q== contains a path separator

**Comment by bafoed** [comment]
Исправлю в ближайшем обновлении.

**Comment by bafoed** [comment]
Должно быть исправлено в 1.0.1.
