### ISSUE TITLE
Необработанная ошибка

### ISSUE THREAD

**Issue by wesdxxx** [bafoed/plantain#7]
HTC one m8 (андроид 5.0.1.)  В списке устройств указано Компания NXP PN544,но  при считывании карты приложение выдает:
Attempt to invoke virtual method short android os Bundle.  getShort(java lang.  String)  on a null object reference

**Comment by bafoed** [comment]
Попробуй версию 1.0.2, возможно заработает.

**Comment by bafoed** [comment]
Обсуждение ошибки с _ android.os.Bundle.getShort(java.lang.String)_ переносится в #5.
