### ISSUE TITLE
поддержка таких карт

### ISSUE THREAD

**Issue by NoEndOutcry** [bafoed/plantain#9]
Асус зенфон 2 551. В таком варианте ничего не поделать?

![photo_2017-03-18_23-15-50](https://cloud.githubusercontent.com/assets/26510699/24075673/dc239108-0c30-11e7-83aa-34b3928b79f4.jpg)
![photo_2017-03-18_23-15-44](https://cloud.githubusercontent.com/assets/26510699/24075675/dcc1959c-0c30-11e7-9e97-2ff14300b6dc.jpg)

**Comment by bafoed** [comment]
Broadcom BCM20795, к сожалению ничего.
